<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reporting_button</name>
   <tag></tag>
   <elementGuidId>43af82e0-fe10-4693-adee-7307a9dc21cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li#ui-id-5 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;ui-id-5&quot;)/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1567784042965</value>
   </webElementProperties>
</WebElementEntity>
